export enum ConsumableLogTypes{
    CONSUMABLE_MATERIAL_IN = 1,
    FREE_CONSUMABLE_MATERIAL_OUT = 2,
    CONSUMABLE_MATERIAL_REQUEST = 4,
    CONSUMABLE_MATERIAL_RECEIVED = 5,
    CONSUMABLE_MATERIAL_REQUEST_CANCEL = 6
}