export const MENU_DASHBOARD = "Dashboard";
export const MENU_LOGIN="Login";
export const MENU_DEFINITIONS="Menu_Definitions";
export const MENU_OPERATIONS="Menu_Operations";
export const MENU_DEPRECIATIONS ="Menu_Depreciations";
export const MENU_MAINTENANCE="Menu_Maintenance";
export const MENU_DEPARTMENTSDEFINITION="Menu_DepartmentDefinition";
export const MENU_LOCATIONDEFINITIONS="Menu_LocationDefinitions";
export const MENU_USERDEFINITIONS="Menu_UserDefinitions";
export const MENU_FIXEDASSETDEFINITIONS="Menu_FixedAssetDefinitions";
export const MENU_FIXEDASSETCATEGORYDEFINITIONS="Menu_FixedAssetCategoryDefinitions";
export const MENU_COMPANYDEFINITONS="Menu_CompanyDefinitions";
export const MENU_CONSUMABLE = "Menu_Consumable";
export const MENU_EXPENSECENTERDEFINITIONS="Menu_ExpenseCenterDefinitions";
export const MENU_MARKDEFINITIONS="Menu_MarkDefinitions";
export const MENU_MODELDEFINITIONS="Menu_ModelDefinitions";
export const MENU_CHECKOUTREASONDEFINITIONS="Menu_CheckOutReasonDefinitions";
export const MENU_ROLEAUTHORIZATIONDEFINITIONS="Menu_RoleAuthorizationDefinitions";

