
export const MENU_DASHBOARD = "Dashboard";
export const MENU_LOGIN = "Login";
export const MENU_DEFINITIONS="Menu_Definitions"
export const MENU_OPERATIONS="Menu_Operations"
export const MENU_DEPRECIATIONS="Menu_Depreciations"
export const MENU_MAINTENANCE="Menu_Maintenance"
export const MENU_DEPARTMENTDEFINITIONS="Menu_DepartmentDefinitions"
export const MENU_LOCATIONDEFINITIONS="Menu_LocationDefinitions"
export const MENU_USERDEFINITIONS="Menu_UserDefinitions"
export const MENU_FIXEDASSETDEFINITIONS="Menu_FixedAssetDefinitions"
export const MENU_FIXEDASSETCATEGORYDEFINITIONS="Menu_FixedAssetCategoryDefinitions"
export const MENU_COMPANYDEFINITIONS="Menu_CompanyDefinitions"
export const MENU_CONSUMABLE="Menu_Consumable"
export const MENU_ROLEAUTHORIZATIONDEFINITIONS="Menu_RoleAuthorizationDefinitions"
export const MENU_ROLEDEFINITIONS="Menu_RoleDefinitions"
export const MENU_FIXEDASSETCARDPROPERTY="Menu_FixedAssetCardProperty"
export const MENU_EXPENSECENTERDEFINITIONS="Menu_ExpenseCenterDefinitions"
export const MENU_CHECKOUTREASONLISTS="Menu_CheckOutReasonLists"
export const MENU_CHECKOUTSUSPENDEDLIST="Menu_CheckOutSuspendedList"
export const MENU_AGREEMENTS="Menu_Agreements"
export const MENU_FIXEDASSETCARDS="Menu_FixedAssetCards"
export const MENU_FIXEDASSETBRANDS="Menu_FixedAssetBrands"
export const MENU_FIXEDASSETMODELS="Menu_FixedAssetModels"
export const MENU_FIXEDASSETOPERATIONS="Menu_FixedAssetOperations"
export const MENU_SUSPENDEDFIXEDASSETS="Menu_SuspendedFixedAssets"
export const MENU_LOSTFIXEDASSETS="Menu_LostFixedAssets"
export const MENU_CHECKEDOUTFIXEDASSETS="MENU_CheckedOutFixedAssets"
export const MENU_CYCLECOUNTS="Menu_CycleCounts"
export const MENU_CYCLECOUNTPLANNIG="Menu_CycleCountPlannig"
export const MENU_FIXEDASSETSTATUS = "Menu_FixedAssetStatus";
export const MENU_FIXEDASSETRELATIONSHIP = "Menu_FixedAssetRelationship";
export const MENU_TRANSACTIONLIST="Menu_TransactionList";
// export const MENU_USERSETTINGS="Menu_UserSettings";
export const MENU_TERMINAL = "Menu_CycleCountTerminal";
