/*export const MENU_DASHBOARD = "Dashboard";
export const MENU_LOGIN = "Login";
export const MENU_DEFINITIONS = "Menu_Definitions";
export const MENU_OPERATIONS = "Menu_Operations";
export const MENU_DEPRECIATIONS = "Menu_Depreciations";
export const MENU_MAINTENANCE = "Menu_Maintenance";
export const MENU_DEPARTMENTSDEFINITIONS = "Menu_DepartmentDefinitions";
export const MENU_LOCATIONDEFINITIONS = "Menu_LocationDefinitions";
export const MENU_USERDEFINITIONS = "Menu_UserDefinitions";
export const MENU_FIXEDASSETDEFINITIONS = "Menu_FixedAssetDefinitions";
export const MENU_FIXEDASSETCARDDEFINITIONS = "Menu_FixedAssetCardDefinitions";
export const MENU_FIXEDASSETCARDCATEGORYDEFINITIONS = "Menu_FixedAssetCategoryDefinitions";
export const MENU_COMPANYDEFINITONS = "Menu_CompanyDefinitions";
export const MENU_CONSUMABLE = "Menu_Consumable";
export const MENU_ROLEAUTHORIZATIONDEFINITIONS = "Menu_RoleAuthorizationDefinitions";
export const MENU_ROLEDEFINITIONS = "Menu_RoleDefinitions";
export const MENU_FIXEDASSETCARDPROPERTYDEFINITIONS = "Menu_FixedAssetCardProperty";
export const MENU_EXPENSECENTERDEFINITIONS = "Menu_ExpenseCenterDefinitions";
export const MENU_CHECKOUTREASONDEFINITIONS = "Menu_CheckOutReasonLists";
export const MENU_MARKDEFINITIONS = "Menu_MarkDefinitions";
export const MENU_MODELDEFINITIONS = "Menu_ModelDefinitions";
export const MENU_AGREEMENTS = "Menu_Agreements";
export const MENU_FIXEDASSETCARDBRANDDEFINITIONS = "Menu_FixedAssetCardBrandDefinitions";
export const MENU_FIXEDASSETCARDMODELS = "Menu_FixedAssetCardModels";
export const MENU_FIXEDASSET = "Menu_FixedAsset";
export const MENU_STATUSLIST = "Menu_StatusList";
export const MENU_FIXEDASSETOPERATIONS = "Menu_FixedAssetOperations";
export const MENU_SUSPENSION = "Menu_SuspensionDefinitions";
export const MENU_SUSPENDEDFIXEDASSET = "Menu_SuspendedFixedAsset";
export const MENU_CHECKOUTFIXEDASSET = "Menu_Checkout_FixedAsset";
export const MENU_LOSTFIXEDASSET = "Menu_Lost_FixedAsset";
*/

export const MENU_DASHBOARD = "Dashboard";
export const MENU_LOGIN = "Login";
export const MENU_DEFINITIONS="Menu_Definitions"
export const MENU_OPERATIONS="Menu_Operations"
export const MENU_DEPRECIATIONS="Menu_Depreciations"
export const MENU_MAINTENANCE="Menu_Maintenance"
export const MENU_DEPARTMENTDEFINITIONS="Menu_DepartmentDefinitions"
export const MENU_LOCATIONDEFINITIONS="Menu_LocationDefinitions"
export const MENU_USERDEFINITIONS="Menu_UserDefinitions"
export const MENU_FIXEDASSETDEFINITIONS="Menu_FixedAssetDefinitions"
export const MENU_FIXEDASSETCATEGORYDEFINITIONS="Menu_FixedAssetCategoryDefinitions"
export const MENU_COMPANYDEFINITIONS="Menu_CompanyDefinitions"
export const MENU_CONSUMABLE="Menu_Consumable"
export const MENU_ROLEAUTHORIZATIONDEFINITIONS="Menu_RoleAuthorizationDefinitions"
export const MENU_ROLEDEFINITIONS="Menu_RoleDefinitions"
export const MENU_FIXEDASSETCARDPROPERTY="Menu_FixedAssetCardProperty"
export const MENU_EXPENSECENTERDEFINITIONS="Menu_ExpenseCenterDefinitions"
export const MENU_CHECKOUTREASONLISTS="Menu_CheckOutReasonLists"
export const MENU_CHECKOUTSUSPENDEDLIST="Menu_CheckOutSuspendedList"
export const MENU_AGREEMENTS="Menu_Agreements"
export const MENU_FIXEDASSETCARDS="Menu_FixedAssetCards"
export const MENU_FIXEDASSETBRANDS="Menu_FixedAssetBrands"
export const MENU_FIXEDASSETMODELS="Menu_FixedAssetModels"
export const MENU_FIXEDASSETOPERATIONS="Menu_FixedAssetOperations"
export const MENU_SUSPENDEDFIXEDASSETS="Menu_SuspendedFixedAssets"
export const MENU_LOSTFIXEDASSETS="Menu_LostFixedAssets"
export const MENU_CHECKEDOUTFIXEDASSETS="MENU_CheckedOutFixedAssets"
export const MENU_CYCLECOUNTS="Menu_CycleCounts"
export const MENU_CYCLECOUNTPLANNIG="Menu_CycleCountPlannig"
export const MENU_CYCLECOUNTRESULTS="Menu_CycleCountResults"
export const MENU_CYCLECOUNTSTATUS="Menu_CycleCountStatus"
export const MENU_FIXEDASSETSTATUS = "Menu_FixedAssetStatus";
export const MENU_FIXEDASSETRELATIONSHIP = "Menu_FixedAssetRelationship";
export const MENU_TRANSACTIONLIST="Menu_TransactionList";
// export const MENU_USERSETTINGS="Menu_UserSettings";
